### ISSUE TITLE
Render the sprint content as a JupyterBook

### ISSUE THREAD

**Issue by colliand** [opensciency/sprint-content#2]
During the 3rd Eddy Symposium, @fperez created [this documented pull request](https://github.com/jack-eddy-symposium/exoplanetary-impact/pull/2) to show how to continuously render a repo with .md and .ipynb files as a JupyterBook. I suggest that it would be useful to have the sprint-content accessible as a JupyterBook. 

Thank you to all the contributors to this excellent collection of resources!

**Comment by libcce** [comment]
@colliand we've decided to move forward with a minimal Markdown release (set for Feb 20th, 2023. But if you would like to fork the content and create a JupyterBooks, that would be great. Thanks!
