### ISSUE TITLE
Add Roadmap

### ISSUE THREAD

**Issue by yochannah** [opensciency/sprint-content#8]
It would be good to share with the world how we'd like to see the future of this work. 

Some possible ideas: 

# Short term (October)

- Tidy up and interlink the markdown files
- community consultation on the content
- set up a JupyterBook as in #2 
- Add CoC
- Add Contributors (@SaranjeetKaur has already done some of this) 
- Add contribution guidelines
- Create a glossary and/or link to other glossaries, like FORRT. 

# Medium term (by end of 2022) 

- define longer term future
- roles - who maintains, who reviews and merges PRs, governance

# Longer term
- Once we've defined what we want to see: how are these roles funded?

----

All: What would YOU add that I missed? (probably loads?)

**Comment by logankilpatrick** [comment]
Not sure if the domain-specific content will tie into this repo, but there were lots of discussions about how we can people to add their content. It would be nice to see comments where you can point people to add their domain-specific scientific stuff into these 6 spots.

**Comment by libcce** [comment]
@logankilpatrick we've decided to move forward with a minimal Markdown release set for Feb 20th, 2023. If you'd like to do more with the material, that will be great.
